name: Deploy to Firebase Hosting Development

on: workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare Google Application Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEV_BASE64 }}" | base64 --decode > "google-application-credentials.json"

      - name: Deploy Firebase Hosting
        run: npm run deploy

      - name: Remove credentials file
        if: success() || failure()
        run: rm google-application-credentials.json
